.TH "BlockyVulkan::Model::Vertex" 3 "Sun Dec 8 2024 18:35:01" "Version 0.1" "VulkanBlock" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockyVulkan::Model::Vertex
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <model\&.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::vector< VkVertexInputBindingDescription > \fBGetBindingDescriptions\fP ()"
.br
.ti -1c
.RI "static std::vector< VkVertexInputAttributeDescription > \fBGetAttributeDescriptions\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "glm::vec2 \fBposition\fP"
.br
.ti -1c
.RI "glm::vec3 \fBcolor\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "std::vector< VkVertexInputAttributeDescription > BlockyVulkan::Model::Vertex::GetAttributeDescriptions ()\fR [static]\fP"

.SS "std::vector< VkVertexInputBindingDescription > BlockyVulkan::Model::Vertex::GetBindingDescriptions ()\fR [static]\fP"

.SH "Member Data Documentation"
.PP 
.SS "glm::vec3 BlockyVulkan::Model::Vertex::color"

.SS "glm::vec2 BlockyVulkan::Model::Vertex::position"


.SH "Author"
.PP 
Generated automatically by Doxygen for VulkanBlock from the source code\&.
