.TH "BlockyVulkan::Device" 3 "Sun Dec 8 2024 18:35:01" "Version 0.1" "VulkanBlock" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockyVulkan::Device
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <device\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDevice\fP (\fBWindow\fP &window)"
.br
.ti -1c
.RI "\fB~Device\fP ()"
.br
.ti -1c
.RI "\fBDevice\fP (const \fBDevice\fP &)=delete"
.br
.ti -1c
.RI "void \fBoperator=\fP (const \fBDevice\fP &)=delete"
.br
.ti -1c
.RI "\fBDevice\fP (\fBDevice\fP &&)=delete"
.br
.ti -1c
.RI "\fBDevice\fP & \fBoperator=\fP (\fBDevice\fP &&)=delete"
.br
.ti -1c
.RI "VkCommandPool \fBgetCommandPool\fP ()"
.br
.ti -1c
.RI "VkDevice \fBdevice\fP ()"
.br
.ti -1c
.RI "VkSurfaceKHR \fBsurface\fP ()"
.br
.ti -1c
.RI "VkQueue \fBgraphicsQueue\fP ()"
.br
.ti -1c
.RI "VkQueue \fBpresentQueue\fP ()"
.br
.ti -1c
.RI "\fBSwapChainSupportDetails\fP \fBgetSwapChainSupport\fP ()"
.br
.ti -1c
.RI "uint32_t \fBfindMemoryType\fP (uint32_t typeFilter, VkMemoryPropertyFlags \fBproperties\fP)"
.br
.ti -1c
.RI "\fBQueueFamilyIndices\fP \fBfindPhysicalQueueFamilies\fP ()"
.br
.ti -1c
.RI "VkFormat \fBfindSupportedFormat\fP (const std::vector< VkFormat > &candidates, VkImageTiling tiling, VkFormatFeatureFlags features)"
.br
.ti -1c
.RI "void \fBcreateBuffer\fP (VkDeviceSize size, VkBufferUsageFlags usage, VkMemoryPropertyFlags \fBproperties\fP, VkBuffer &buffer, VkDeviceMemory &bufferMemory)"
.br
.ti -1c
.RI "VkCommandBuffer \fBbeginSingleTimeCommands\fP ()"
.br
.ti -1c
.RI "void \fBendSingleTimeCommands\fP (VkCommandBuffer commandBuffer)"
.br
.ti -1c
.RI "void \fBcopyBuffer\fP (VkBuffer srcBuffer, VkBuffer dstBuffer, VkDeviceSize size)"
.br
.ti -1c
.RI "void \fBcopyBufferToImage\fP (VkBuffer buffer, VkImage image, uint32_t width, uint32_t height, uint32_t layerCount)"
.br
.ti -1c
.RI "void \fBcreateImageWithInfo\fP (const VkImageCreateInfo &imageInfo, VkMemoryPropertyFlags \fBproperties\fP, VkImage &image, VkDeviceMemory &imageMemory)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const bool \fBenableValidationLayers\fP = true"
.br
.ti -1c
.RI "VkPhysicalDeviceProperties \fBproperties\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BlockyVulkan::Device::Device (\fBWindow\fP & window)"

.SS "BlockyVulkan::Device::~Device ()"

.SS "BlockyVulkan::Device::Device (const \fBDevice\fP & )\fR [delete]\fP"

.SS "BlockyVulkan::Device::Device (\fBDevice\fP && )\fR [delete]\fP"

.SH "Member Function Documentation"
.PP 
.SS "VkCommandBuffer BlockyVulkan::Device::beginSingleTimeCommands ()"

.SS "void BlockyVulkan::Device::copyBuffer (VkBuffer srcBuffer, VkBuffer dstBuffer, VkDeviceSize size)"

.SS "void BlockyVulkan::Device::copyBufferToImage (VkBuffer buffer, VkImage image, uint32_t width, uint32_t height, uint32_t layerCount)"

.SS "void BlockyVulkan::Device::createBuffer (VkDeviceSize size, VkBufferUsageFlags usage, VkMemoryPropertyFlags properties, VkBuffer & buffer, VkDeviceMemory & bufferMemory)"

.SS "void BlockyVulkan::Device::createImageWithInfo (const VkImageCreateInfo & imageInfo, VkMemoryPropertyFlags properties, VkImage & image, VkDeviceMemory & imageMemory)"

.SS "VkDevice BlockyVulkan::Device::device ()\fR [inline]\fP"

.SS "void BlockyVulkan::Device::endSingleTimeCommands (VkCommandBuffer commandBuffer)"

.SS "uint32_t BlockyVulkan::Device::findMemoryType (uint32_t typeFilter, VkMemoryPropertyFlags properties)"

.SS "\fBQueueFamilyIndices\fP BlockyVulkan::Device::findPhysicalQueueFamilies ()\fR [inline]\fP"

.SS "VkFormat BlockyVulkan::Device::findSupportedFormat (const std::vector< VkFormat > & candidates, VkImageTiling tiling, VkFormatFeatureFlags features)"

.SS "VkCommandPool BlockyVulkan::Device::getCommandPool ()\fR [inline]\fP"

.SS "\fBSwapChainSupportDetails\fP BlockyVulkan::Device::getSwapChainSupport ()\fR [inline]\fP"

.SS "VkQueue BlockyVulkan::Device::graphicsQueue ()\fR [inline]\fP"

.SS "void BlockyVulkan::Device::operator= (const \fBDevice\fP & )\fR [delete]\fP"

.SS "\fBDevice\fP & BlockyVulkan::Device::operator= (\fBDevice\fP && )\fR [delete]\fP"

.SS "VkQueue BlockyVulkan::Device::presentQueue ()\fR [inline]\fP"

.SS "VkSurfaceKHR BlockyVulkan::Device::surface ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "const bool BlockyVulkan::Device::enableValidationLayers = true"

.SS "VkPhysicalDeviceProperties BlockyVulkan::Device::properties"


.SH "Author"
.PP 
Generated automatically by Doxygen for VulkanBlock from the source code\&.
