.TH "BlockyVulkan::SwapChainSupportDetails" 3 "Sun Dec 8 2024 18:35:01" "Version 0.1" "VulkanBlock" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockyVulkan::SwapChainSupportDetails
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <device\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "VkSurfaceCapabilitiesKHR \fBcapabilities\fP"
.br
.ti -1c
.RI "std::vector< VkSurfaceFormatKHR > \fBformats\fP"
.br
.ti -1c
.RI "std::vector< VkPresentModeKHR > \fBpresentModes\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "VkSurfaceCapabilitiesKHR BlockyVulkan::SwapChainSupportDetails::capabilities"

.SS "std::vector<VkSurfaceFormatKHR> BlockyVulkan::SwapChainSupportDetails::formats"

.SS "std::vector<VkPresentModeKHR> BlockyVulkan::SwapChainSupportDetails::presentModes"


.SH "Author"
.PP 
Generated automatically by Doxygen for VulkanBlock from the source code\&.
