.TH "BlockyVulkan::FirstTest" 3 "Sun Dec 8 2024 18:35:01" "Version 0.1" "VulkanBlock" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockyVulkan::FirstTest
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <first_test\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFirstTest\fP ()"
.br
.ti -1c
.RI "\fB~FirstTest\fP ()"
.br
.ti -1c
.RI "\fBFirstTest\fP (const \fBFirstTest\fP &)=delete"
.br
.ti -1c
.RI "\fBFirstTest\fP & \fBoperator=\fP (const \fBFirstTest\fP &)=delete"
.br
.ti -1c
.RI "void \fBRun\fP ()"
.br
.ti -1c
.RI "void \fBSierpinski\fP (std::vector< \fBModel::Vertex\fP > &vertices, int depth, glm::vec2 left, glm::vec2 right, glm::vec2 top)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr int \fBWIDTH\fP {800}"
.br
.ti -1c
.RI "static constexpr int \fBHEIGHT\fP {600}"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BlockyVulkan::FirstTest::FirstTest ()"

.SS "BlockyVulkan::FirstTest::~FirstTest ()"

.SS "BlockyVulkan::FirstTest::FirstTest (const \fBFirstTest\fP & )\fR [delete]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBFirstTest\fP & BlockyVulkan::FirstTest::operator= (const \fBFirstTest\fP & )\fR [delete]\fP"

.SS "void BlockyVulkan::FirstTest::Run ()"

.SS "void BlockyVulkan::FirstTest::Sierpinski (std::vector< \fBModel::Vertex\fP > & vertices, int depth, glm::vec2 left, glm::vec2 right, glm::vec2 top)"

.SH "Member Data Documentation"
.PP 
.SS "int BlockyVulkan::FirstTest::HEIGHT {600}\fR [static]\fP, \fR [constexpr]\fP"

.SS "int BlockyVulkan::FirstTest::WIDTH {800}\fR [static]\fP, \fR [constexpr]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VulkanBlock from the source code\&.
