.TH "BlockyVulkan::Transform2D_Component" 3 "Sun Dec 8 2024 18:35:01" "Version 0.1" "VulkanBlock" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockyVulkan::Transform2D_Component
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <game_object\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "glm::mat2 \fBmat2\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "glm::vec2 \fBtranslation\fP {}"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "glm::mat2 BlockyVulkan::Transform2D_Component::mat2 ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "glm::vec2 BlockyVulkan::Transform2D_Component::translation {}"


.SH "Author"
.PP 
Generated automatically by Doxygen for VulkanBlock from the source code\&.
