.TH "BlockyVulkan::PipelineConfigInfo" 3 "Sun Dec 8 2024 18:35:01" "Version 0.1" "VulkanBlock" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockyVulkan::PipelineConfigInfo
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <pipeline\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPipelineConfigInfo\fP ()=default"
.br
.ti -1c
.RI "\fBPipelineConfigInfo\fP & \fBoperator=\fP (const \fBPipelineConfigInfo\fP &)=delete"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "VkPipelineViewportStateCreateInfo \fBviewportInfo\fP"
.br
.ti -1c
.RI "VkPipelineInputAssemblyStateCreateInfo \fBinputAssemblyInfo\fP"
.br
.ti -1c
.RI "VkPipelineRasterizationStateCreateInfo \fBrasterizationInfo\fP"
.br
.ti -1c
.RI "VkPipelineMultisampleStateCreateInfo \fBmultisampleInfo\fP"
.br
.ti -1c
.RI "VkPipelineColorBlendStateCreateInfo \fBcolorBlendInfo\fP"
.br
.ti -1c
.RI "VkPipelineDepthStencilStateCreateInfo \fBdepthStencilInfo\fP"
.br
.ti -1c
.RI "VkPipelineColorBlendAttachmentState \fBcolorBlendAttachment\fP"
.br
.ti -1c
.RI "std::vector< VkDynamicState > \fBdynamicStateEnables\fP"
.br
.ti -1c
.RI "VkPipelineDynamicStateCreateInfo \fBdynamicStateInfo\fP"
.br
.ti -1c
.RI "VkPipelineLayout \fBpipelineLayout\fP = nullptr"
.br
.ti -1c
.RI "VkRenderPass \fBrenderPass\fP = nullptr"
.br
.ti -1c
.RI "uint32_t \fBsubpass\fP = 0"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BlockyVulkan::PipelineConfigInfo::PipelineConfigInfo ()\fR [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBPipelineConfigInfo\fP & BlockyVulkan::PipelineConfigInfo::operator= (const \fBPipelineConfigInfo\fP & )\fR [delete]\fP"

.SH "Member Data Documentation"
.PP 
.SS "VkPipelineColorBlendAttachmentState BlockyVulkan::PipelineConfigInfo::colorBlendAttachment"

.SS "VkPipelineColorBlendStateCreateInfo BlockyVulkan::PipelineConfigInfo::colorBlendInfo"

.SS "VkPipelineDepthStencilStateCreateInfo BlockyVulkan::PipelineConfigInfo::depthStencilInfo"

.SS "std::vector<VkDynamicState> BlockyVulkan::PipelineConfigInfo::dynamicStateEnables"

.SS "VkPipelineDynamicStateCreateInfo BlockyVulkan::PipelineConfigInfo::dynamicStateInfo"

.SS "VkPipelineInputAssemblyStateCreateInfo BlockyVulkan::PipelineConfigInfo::inputAssemblyInfo"

.SS "VkPipelineMultisampleStateCreateInfo BlockyVulkan::PipelineConfigInfo::multisampleInfo"

.SS "VkPipelineLayout BlockyVulkan::PipelineConfigInfo::pipelineLayout = nullptr"

.SS "VkPipelineRasterizationStateCreateInfo BlockyVulkan::PipelineConfigInfo::rasterizationInfo"

.SS "VkRenderPass BlockyVulkan::PipelineConfigInfo::renderPass = nullptr"

.SS "uint32_t BlockyVulkan::PipelineConfigInfo::subpass = 0"

.SS "VkPipelineViewportStateCreateInfo BlockyVulkan::PipelineConfigInfo::viewportInfo"


.SH "Author"
.PP 
Generated automatically by Doxygen for VulkanBlock from the source code\&.
