.TH "BlockyVulkan::SimplePushConstantData" 3 "Sun Dec 8 2024 18:35:01" "Version 0.1" "VulkanBlock" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockyVulkan::SimplePushConstantData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "glm::mat2 \fBtransform\fP {1\&.f}"
.br
.ti -1c
.RI "glm::vec2 \fBoffset\fP"
.br
.ti -1c
.RI "glm::vec3 \fBcolor\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "glm::vec3 BlockyVulkan::SimplePushConstantData::color"

.SS "glm::vec2 BlockyVulkan::SimplePushConstantData::offset"

.SS "glm::mat2 BlockyVulkan::SimplePushConstantData::transform {1\&.f}"


.SH "Author"
.PP 
Generated automatically by Doxygen for VulkanBlock from the source code\&.
