.TH "BlockyVulkan" 3 "Sun Dec 8 2024 18:35:01" "Version 0.1" "VulkanBlock" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockyVulkan
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDevice\fP"
.br
.ti -1c
.RI "class \fBFirstTest\fP"
.br
.ti -1c
.RI "class \fBGameObject\fP"
.br
.ti -1c
.RI "class \fBModel\fP"
.br
.ti -1c
.RI "class \fBPipeline\fP"
.br
.ti -1c
.RI "struct \fBPipelineConfigInfo\fP"
.br
.ti -1c
.RI "struct \fBQueueFamilyIndices\fP"
.br
.ti -1c
.RI "struct \fBSimplePushConstantData\fP"
.br
.ti -1c
.RI "class \fBSwapChain\fP"
.br
.ti -1c
.RI "struct \fBSwapChainSupportDetails\fP"
.br
.ti -1c
.RI "struct \fBTransform2D_Component\fP"
.br
.ti -1c
.RI "class \fBWindow\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "VkResult \fBCreateDebugUtilsMessengerEXT\fP (VkInstance instance, const VkDebugUtilsMessengerCreateInfoEXT *pCreateInfo, const VkAllocationCallbacks *pAllocator, VkDebugUtilsMessengerEXT *pDebugMessenger)"
.br
.ti -1c
.RI "void \fBDestroyDebugUtilsMessengerEXT\fP (VkInstance instance, VkDebugUtilsMessengerEXT debugMessenger, const VkAllocationCallbacks *pAllocator)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "VkResult BlockyVulkan::CreateDebugUtilsMessengerEXT (VkInstance instance, const VkDebugUtilsMessengerCreateInfoEXT * pCreateInfo, const VkAllocationCallbacks * pAllocator, VkDebugUtilsMessengerEXT * pDebugMessenger)"

.SS "void BlockyVulkan::DestroyDebugUtilsMessengerEXT (VkInstance instance, VkDebugUtilsMessengerEXT debugMessenger, const VkAllocationCallbacks * pAllocator)"

.SH "Author"
.PP 
Generated automatically by Doxygen for VulkanBlock from the source code\&.
