.TH "BlockyVulkan::QueueFamilyIndices" 3 "Sun Dec 8 2024 18:35:01" "Version 0.1" "VulkanBlock" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockyVulkan::QueueFamilyIndices
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <device\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBisComplete\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBgraphicsFamily\fP"
.br
.ti -1c
.RI "uint32_t \fBpresentFamily\fP"
.br
.ti -1c
.RI "bool \fBgraphicsFamilyHasValue\fP = false"
.br
.ti -1c
.RI "bool \fBpresentFamilyHasValue\fP = false"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bool BlockyVulkan::QueueFamilyIndices::isComplete ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "uint32_t BlockyVulkan::QueueFamilyIndices::graphicsFamily"

.SS "bool BlockyVulkan::QueueFamilyIndices::graphicsFamilyHasValue = false"

.SS "uint32_t BlockyVulkan::QueueFamilyIndices::presentFamily"

.SS "bool BlockyVulkan::QueueFamilyIndices::presentFamilyHasValue = false"


.SH "Author"
.PP 
Generated automatically by Doxygen for VulkanBlock from the source code\&.
