.TH "model.hpp" 3 "Sun Dec 8 2024 18:35:01" "Version 0.1" "VulkanBlock" \" -*- nroff -*-
.ad l
.nh
.SH NAME
model.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./device/device\&.hpp'\fP
.br
\fR#include <vulkan/vulkan\&.h>\fP
.br
\fR#include <glm/glm\&.hpp>\fP
.br
\fR#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBlockyVulkan::Model\fP"
.br
.ti -1c
.RI "struct \fBBlockyVulkan::Model::Vertex\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBBlockyVulkan\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGLM_FORCE_RADIANS\fP"
.br
.ti -1c
.RI "#define \fBGLM_FORCE_DEPTH_ZERO_TO_ONE\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define GLM_FORCE_DEPTH_ZERO_TO_ONE"

.SS "#define GLM_FORCE_RADIANS"

.SH "Author"
.PP 
Generated automatically by Doxygen for VulkanBlock from the source code\&.
