.TH "window.hpp" 3 "Sun Dec 8 2024 18:35:01" "Version 0.1" "VulkanBlock" \" -*- nroff -*-
.ad l
.nh
.SH NAME
window.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <vulkan/vulkan\&.h>\fP
.br
\fR#include <GLFW/glfw3\&.h>\fP
.br
\fR#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBlockyVulkan::Window\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBBlockyVulkan\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VulkanBlock from the source code\&.
